import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import "./globals.css";
import { createTheme, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import { Analytics } from "@vercel/analytics/next";

// 1. Asegúrate de agregar este flag ↓↓↓
export const metadata: Metadata = {
  title: "Gestión Villa",
  description: "Generated by create next app",
};

const theme = createTheme({});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    // 2. Usa suppressHydrationWarning en <html>
    <html lang="es" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MantineProvider
            theme={theme}
            withCssVariables
            defaultColorScheme="light"
          >
            {children}
            <Analytics />
          </MantineProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
